### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ghost** [norpba/PyARR#1]
### Problem
I was testing the performance issues we talked about and came to the following conclusion:

Commenting the following line of code out will increase the performance of the copy process by about **15x**
https://github.com/norpba/PyARR/blob/0a2d46970190748708512529db01f16a17eae6d3/src/sorter.py#L241

I tested with 3,2GiB of files (3031 files, 3 sub-folders) and got these results:
**current:**
`Sorting completed in 31.56443762779236 seconds.`

**with the line 241 commented out:**
`Sorting completed in 2.088543653488159 seconds.`

This makes sense since we are literally updating the GUI every single time we check a file.

### (Possible) Solution
I made a simple (and buggy) test version that checks it in only 0.01 increments which got me to **2.7** seconds,
so that would certainly be one option.

t. thiif

**Comment by norpba** [comment]
Hi Tiif.

I see, that definitely has a huge impact on the performance. I'm going to try and find a solution where I can have a nice visual representation of the sorting progress without losing too much performance. Although for me, visuals are more important than literal performance, but comparing the completion times that you got (~31 seconds to about 2 seconds) tells me that I need to optimize it. 

Anyway thanks for opening this issue, going to def work on it later.

**Comment by ghost** [comment]
> visuals are more important than literal performance

Certainly, especially for a program that you're not going to be running all the time anyway. 
I just found this interesting enough so I looked into it and wanted to report my findings.

happy hacking
